### ISSUE TITLE
As a <registered user>, I want to <delete a photo> so I can <be sure it no longer exists on the service>.

### ISSUE THREAD

**Issue by JoshuaKoh** [theresaming/PortfolioLife#20]
## Story/Task Details
- [x] From homepage, add a link to "Delete Photos".
- [x] Implement new page which contains a grid layout of all uploaded photos.
- [ ] Implement allowing users to select one or more photos for deletion.
- [ ] Implement "Delete" button at bottom of grid layout.
- [ ] Implement "Are you sure you want to delete x photos?" where x is the number of photos selected.
- [x] Implement removal of uploaded photos from DB.
- [x] Implement dissociation of uploaded photos with user who did the deleting.

## Acceptance Scenarios
Scenario 1: A registered user wants delete photos.
Given: the user is logged in, is on the homepage, and has photos to delete
When: the user clicks on the "Delete Photos" button
Then: the user is sent to the "Delete Photos" grid layout.

Scenario 2: ""
Given: a registered user is on the "Delete Photos" grid layout
When: the user clicks a photo on the layout
Then: the photo is highlighted if it wasn't, and it is deselected if it was highlighted.

Scenario 3: ""
Given: a registered user has selected photos for deletion
When: the user clicks the "Delete" button on the "Delete Photos" grid layout
Then: an "Are you sure you want to delete x photos?" prompt is shown.

Scenario 4: ""
Given: a registered user is viewing the "Are you sure" prompt.
When: the user clicks "Yes"
Then: the DB is updated with the deletion and the user is given a prompt that says "photos deleted", with a link back to the homepage

Scenario 5: ""
Given: a registered user is viewing the "Are you sure" prompt.
When: the user clicks "No"
Then: the "Are you sure" prompt is removed and the user is returned to the grid layout to modify which photos they want deleted. The photos previously selected should still be selected.

## Done Done Criteria
- After deleting photos, the DB does not contain the photos that were deleted.
- After deleting photos, the DB contains the user who uploaded the photos, along with NO  associations between the user and the deleted photos.
- THe UI allows for progression from homepage to homepage.
